name: flutter_tiqlo_clock
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # 状态管理
  flutter_riverpod: 3.3.2
  riverpod_annotation: 4.0.3

  # 路由
  go_router: ^17.5.0

  # 模型序列化
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0

  # 本地存储
  shared_preferences: ^2.5.5

  # 日志
  logger: ^2.7.0

  # 日期格式
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint
  flutter_lints: ^6.0.0
  riverpod_lint: 3.1.4

  # 代码生成
  build_runner: ^2.15.1
  riverpod_generator: 4.0.4
  freezed: ^3.2.3
  json_serializable: ^6.14.1

  # 测试
  shared_preferences_platform_interface: ^2.4.2

flutter:
  uses-material-design: true
